//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyuyo.BL.Resources.SalaryCalculate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesM017 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesM017() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kyuyo.BL.Resources.SalaryCalculate.MessagesM017", typeof(MessagesM017).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hủy xác nhận kết quả lương..
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã kết sổ và gửi mail cho từng nhân viên..
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xác nhận kết quả lương là chính xác..
        /// </summary>
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỷ giá {0} có phần thập phân không phù hợp..
        /// </summary>
        public static string DataTypeJPYRate {
            get {
                return ResourceManager.GetString("DataTypeJPYRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỷ giá {0} phải là số nguyên..
        /// </summary>
        public static string DataTypeUSDRate {
            get {
                return ResourceManager.GetString("DataTypeUSDRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên đã chọn không thuộc công ty đã chỉ định hoặc không có mặt trong kỳ tính lương.
        /// </summary>
        public static string EmployeeNotExist {
            get {
                return ResourceManager.GetString("EmployeeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập Ngày áp dụng tỷ giá {0}..
        /// </summary>
        public static string ErrorEffectiveDt {
            get {
                return ResourceManager.GetString("ErrorEffectiveDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập Ngày áp dụng tỷ giá {0} trước ngày cuối kỳ lương..
        /// </summary>
        public static string ErrorEffectiveDtBeforeSalaryDate {
            get {
                return ResourceManager.GetString("ErrorEffectiveDtBeforeSalaryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa import dữ liệu chấm công, vui lòng import trước khi tính lương..
        /// </summary>
        public static string ErrorImportWorkingTime {
            get {
                return ResourceManager.GetString("ErrorImportWorkingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu chi hộ khác không được lớn hơn 999,999,999.
        /// </summary>
        public static string MaxOther {
            get {
                return ResourceManager.GetString("MaxOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỷ giá {0} không được vượt quá 9,999,999..
        /// </summary>
        public static string MaxRate {
            get {
                return ResourceManager.GetString("MaxRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được lớn hơn 99.
        /// </summary>
        public static string MaxSabbtical {
            get {
                return ResourceManager.GetString("MaxSabbtical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã yêu cầu xác nhận kết quả lương..
        /// </summary>
        public static string Requested {
            get {
                return ResourceManager.GetString("Requested", resourceCulture);
            }
        }
    }
}
