//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyuyo.BL.Resources.SalaryCalculate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsM017 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsM017() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kyuyo.BL.Resources.SalaryCalculate.StringsM017", typeof(StringsM017).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trợ cấp.
        /// </summary>
        public static string Allowance {
            get {
                return ResourceManager.GetString("Allowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lương cơ bản.
        /// </summary>
        public static string BasicSalary {
            get {
                return ResourceManager.GetString("BasicSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các loại thưởng.
        /// </summary>
        public static string Bounus {
            get {
                return ResourceManager.GetString("Bounus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tính toàn công ty.
        /// </summary>
        public static string CalculateAllBtn {
            get {
                return ResourceManager.GetString("CalculateAllBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tính lương 1 nhân viên.
        /// </summary>
        public static string CalculateEmployeeBtn {
            get {
                return ResourceManager.GetString("CalculateEmployeeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt đầu tính lương (Khóa dữ liệu).
        /// </summary>
        public static string Closing {
            get {
                return ResourceManager.GetString("Closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết sổ.
        /// </summary>
        public static string ClosingBtn {
            get {
                return ResourceManager.GetString("ClosingBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt đầu/Kết thúc tính lương.
        /// </summary>
        public static string ClosingTxt {
            get {
                return ResourceManager.GetString("ClosingTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        public static string ConfirmBtn {
            get {
                return ResourceManager.GetString("ConfirmBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày áp dụng.
        /// </summary>
        public static string EffectiveDt {
            get {
                return ResourceManager.GetString("EffectiveDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất báo cáo.
        /// </summary>
        public static string ExportReportBtn {
            get {
                return ResourceManager.GetString("ExportReportBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất bảng lương.
        /// </summary>
        public static string ExportSalary {
            get {
                return ResourceManager.GetString("ExportSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày đầu kỳ lương.
        /// </summary>
        public static string FirstDayCalSal {
            get {
                return ResourceManager.GetString("FirstDayCalSal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy tỷ giá tháng trước.
        /// </summary>
        public static string GetPrevMonthRateBtn {
            get {
                return ResourceManager.GetString("GetPrevMonthRateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy tỉ giá tháng trước.
        /// </summary>
        public static string GetRate {
            get {
                return ResourceManager.GetString("GetRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm tính lương.
        /// </summary>
        public static string GroupCalculate {
            get {
                return ResourceManager.GetString("GroupCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Working Time.
        /// </summary>
        public static string ImportWTBtn {
            get {
                return ResourceManager.GetString("ImportWTBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPY.
        /// </summary>
        public static string JPY {
            get {
                return ResourceManager.GetString("JPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng năm.
        /// </summary>
        public static string MonthYear {
            get {
                return ResourceManager.GetString("MonthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày phép 100%.
        /// </summary>
        public static string NumDayCal100 {
            get {
                return ResourceManager.GetString("NumDayCal100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày phép 300%.
        /// </summary>
        public static string NumDayCal300 {
            get {
                return ResourceManager.GetString("NumDayCal300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết thúc tính lương (Mở dữ liệu).
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu chi hộ khác.
        /// </summary>
        public static string OtherPay {
            get {
                return ResourceManager.GetString("OtherPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diễn giải của thu chi hộ khác.
        /// </summary>
        public static string OtherPayDescription {
            get {
                return ResourceManager.GetString("OtherPayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị thu chi hộ khác.
        /// </summary>
        public static string OtherUnit {
            get {
                return ResourceManager.GetString("OtherUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lọc nhân viên.
        /// </summary>
        public static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỷ giá.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu xác nhận.
        /// </summary>
        public static string ReConfirm {
            get {
                return ResourceManager.GetString("ReConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string Regist {
            get {
                return ResourceManager.GetString("Regist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thưởng.
        /// </summary>
        public static string RegistBounusBtn {
            get {
                return ResourceManager.GetString("RegistBounusBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string RegistBtn {
            get {
                return ResourceManager.GetString("RegistBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lương thực lĩnh.
        /// </summary>
        public static string SalaryAmount {
            get {
                return ResourceManager.GetString("SalaryAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền truy thu/truy lĩnh.
        /// </summary>
        public static string SalaryArrearAmount {
            get {
                return ResourceManager.GetString("SalaryArrearAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truy thu/truy lĩnh.
        /// </summary>
        public static string SalaryArrearBtn {
            get {
                return ResourceManager.GetString("SalaryArrearBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách lương nhân viên.
        /// </summary>
        public static string SalaryList {
            get {
                return ResourceManager.GetString("SalaryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tính lương.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy xác nhận.
        /// </summary>
        public static string UnConfirmBtn {
            get {
                return ResourceManager.GetString("UnConfirmBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD.
        /// </summary>
        public static string USD {
            get {
                return ResourceManager.GetString("USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VND.
        /// </summary>
        public static string VND {
            get {
                return ResourceManager.GetString("VND", resourceCulture);
            }
        }
    }
}
