//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyuyo.BL.Resources.Dependent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesM011 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesM011() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kyuyo.BL.Resources.Dependent.MessagesM011", typeof(MessagesM011).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} dữ liệu Ngày sinh người phụ thuộc phải theo định dạng dd/MM/yyyy.
        /// </summary>
        public static string ErrorBirthDtFormatNotCorrect {
            get {
                return ResourceManager.GetString("ErrorBirthDtFormatNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Ngày sinh người phụ thuộc không được là ngày tương lai.
        /// </summary>
        public static string ErrorBirthDtIsFutureDt {
            get {
                return ResourceManager.GetString("ErrorBirthDtIsFutureDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File đã chọn không đúng định dạng, vui lòng click nút &quot;Xuất Template&quot; để lấy file có định dạng đúng.
        /// </summary>
        public static string ErrorColNumNotCorrect {
            get {
                return ResourceManager.GetString("ErrorColNumNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Mã số thuế/CMND/Hộ chiếu/Giấy khai sinh của người phụ thuộc đã tồn tại.
        /// </summary>
        public static string ErrorDataExistOnDB {
            get {
                return ResourceManager.GetString("ErrorDataExistOnDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Họ và tên người phụ thuộc không được rỗng.
        /// </summary>
        public static string ErrorDependentEmpty {
            get {
                return ResourceManager.GetString("ErrorDependentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} MST của người phụ thuộc không được quá 20 ký tự.
        /// </summary>
        public static string ErrorDependentTaxCodeToLong {
            get {
                return ResourceManager.GetString("ErrorDependentTaxCodeToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Họ và tên người phụ thuộc không được quá 100 ký tự.
        /// </summary>
        public static string ErrorDependentTooLong {
            get {
                return ResourceManager.GetString("ErrorDependentTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Họ và tên người nộp thuế không được rỗng.
        /// </summary>
        public static string ErrorEmployeeNameEmpty {
            get {
                return ResourceManager.GetString("ErrorEmployeeNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} có Họ và tên người nộp thuế không tồn tại.
        /// </summary>
        public static string ErrorEmpNotExist {
            get {
                return ResourceManager.GetString("ErrorEmpNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số thuế/CMND/Hộ chiếu/Giấy khai sinh của người phụ thuộc đã tồn tại.
        /// </summary>
        public static string ErrorExist {
            get {
                return ResourceManager.GetString("ErrorExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File được chọn không đúng định dạng, vui lòng chọn file Excel để import.
        /// </summary>
        public static string ErrorFileFormatNotCorrect {
            get {
                return ResourceManager.GetString("ErrorFileFormatNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File đã chọn không có dữ liệu để import.
        /// </summary>
        public static string ErrorFileIsEmpty {
            get {
                return ResourceManager.GetString("ErrorFileIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Tháng bắt đầu  tính giảm trừ không được rỗng.
        /// </summary>
        public static string ErrorFromMonthEmpty {
            get {
                return ResourceManager.GetString("ErrorFromMonthEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} dữ liệu {1} phải theo định dạng MM/yyyy.
        /// </summary>
        public static string ErrorFromMonthFormatNotCorrect {
            get {
                return ResourceManager.GetString("ErrorFromMonthFormatNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Tháng bắt đầu tính giảm trừ phải trước tháng kết thúc tính giảm trừ.
        /// </summary>
        public static string ErrorFromMonthIsFutureDt {
            get {
                return ResourceManager.GetString("ErrorFromMonthIsFutureDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} CMND/Hộ chiếu người phụ thuộc không được quá 20 ký tự.
        /// </summary>
        public static string ErrorIdPassportToLong {
            get {
                return ResourceManager.GetString("ErrorIdPassportToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} có Mã Quốc tịch của người phụ thuộc không tồn tại.
        /// </summary>
        public static string ErrorNationarityNotExist {
            get {
                return ResourceManager.GetString("ErrorNationarityNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Mã Quốc tịch của người phụ thuộc không được quá 20 ký tự.
        /// </summary>
        public static string ErrorNationarityTaxCodeToLong {
            get {
                return ResourceManager.GetString("ErrorNationarityTaxCodeToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Quyển số giấy khai sinh không được quá 10 ký tự.
        /// </summary>
        public static string ErrorNumberBookToLong {
            get {
                return ResourceManager.GetString("ErrorNumberBookToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Số giấy khai sinh không được quá 10 ký tự.
        /// </summary>
        public static string ErrorNumberToLong {
            get {
                return ResourceManager.GetString("ErrorNumberToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} có Mã Tỉnh/Thành phố không tồn tại.
        /// </summary>
        public static string ErrorRegCityNotExist {
            get {
                return ResourceManager.GetString("ErrorRegCityNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Mã Tỉnh/Thành phố không được quá 20 ký tự.
        /// </summary>
        public static string ErrorRegCityToLong {
            get {
                return ResourceManager.GetString("ErrorRegCityToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} có Mã Quốc gia không tồn tại.
        /// </summary>
        public static string ErrorRegCountryNotExist {
            get {
                return ResourceManager.GetString("ErrorRegCountryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Mã Quốc gia không được quá 20 ký tự.
        /// </summary>
        public static string ErrorRegCountryToLong {
            get {
                return ResourceManager.GetString("ErrorRegCountryToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} có Mã Quận/Huyện không tồn tại.
        /// </summary>
        public static string ErrorRegDistrictNotExist {
            get {
                return ResourceManager.GetString("ErrorRegDistrictNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Mã Quận/Huyện không được quá 20 ký tự.
        /// </summary>
        public static string ErrorRegDistrictToLong {
            get {
                return ResourceManager.GetString("ErrorRegDistrictToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} có Mã Phường/Xã không tồn tại.
        /// </summary>
        public static string ErrorRegWardNotExist {
            get {
                return ResourceManager.GetString("ErrorRegWardNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Mã Phường/Xã không được quá 20 ký tự.
        /// </summary>
        public static string ErrorRegWardToLong {
            get {
                return ResourceManager.GetString("ErrorRegWardToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} có Mã Quan hệ với người nộp thuế không tồn tại.
        /// </summary>
        public static string ErrorRelationshipNotExist {
            get {
                return ResourceManager.GetString("ErrorRelationshipNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Mã Quan hệ với người nộp thuế không được quá 20 ký tự.
        /// </summary>
        public static string ErrorRelationshipToLong {
            get {
                return ResourceManager.GetString("ErrorRelationshipToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} MST của người nộp thuế không được rỗng.
        /// </summary>
        public static string ErrorTaxCodeNotExist {
            get {
                return ResourceManager.GetString("ErrorTaxCodeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} có Họ và tên và mã số thuế không khớp với dữ liệu hệ thống.
        /// </summary>
        public static string ErrorTaxCodeNotMatch {
            get {
                return ResourceManager.GetString("ErrorTaxCodeNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Tháng kết thúc  tính giảm trừ không được rỗng.
        /// </summary>
        public static string ErrorToMonthEmpty {
            get {
                return ResourceManager.GetString("ErrorToMonthEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} dữ liệu {1} phải theo định dạng MM/yyyy.
        /// </summary>
        public static string ErrorToMonthFormatNotCorrect {
            get {
                return ResourceManager.GetString("ErrorToMonthFormatNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày kết thúc giảm trừ phải lớn hơn hoặc bằng ngày bắt đầu giảm trừ.
        /// </summary>
        public static string FutureDate {
            get {
                return ResourceManager.GetString("FutureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import thành công.
        /// </summary>
        public static string ImportSuccess {
            get {
                return ResourceManager.GetString("ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập Số và Quyển số..
        /// </summary>
        public static string InputNumberAndBook {
            get {
                return ResourceManager.GetString("InputNumberAndBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã import {0}/{1} dòng dữ liệu và xuất log kết quả, vui lòng kiểm tra..
        /// </summary>
        public static string ResultImport {
            get {
                return ResourceManager.GetString("ResultImport", resourceCulture);
            }
        }
    }
}
