//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyuyo.BL.Resources.Dependent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsM011 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsM011() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kyuyo.BL.Resources.Dependent.StringsM011", typeof(StringsM011).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin trên giấy khai sinh.
        /// </summary>
        public static string BirthCertificateInfo {
            get {
                return ResourceManager.GetString("BirthCertificateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty.
        /// </summary>
        public static string CompanyCd {
            get {
                return ResourceManager.GetString("CompanyCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời điểm bắt đầu giảm trừ.
        /// </summary>
        public static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời điểm kết thúc giảm trừ.
        /// </summary>
        public static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ phận.
        /// </summary>
        public static string Deparment {
            get {
                return ResourceManager.GetString("Deparment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người phụ thuộc.
        /// </summary>
        public static string Dependent {
            get {
                return ResourceManager.GetString("Dependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin người phụ thuộc.
        /// </summary>
        public static string DependentInfo {
            get {
                return ResourceManager.GetString("DependentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách người phụ thuộc.
        /// </summary>
        public static string DependentList {
            get {
                return ResourceManager.GetString("DependentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên.
        /// </summary>
        public static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số nhân viên.
        /// </summary>
        public static string EmployeeNo {
            get {
                return ResourceManager.GetString("EmployeeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất File Template.
        /// </summary>
        public static string ExportTemplate {
            get {
                return ResourceManager.GetString("ExportTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string Fullname {
            get {
                return ResourceManager.GetString("Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người nộp thuế đã có MST/CMND/Hộ chiếu.
        /// </summary>
        public static string HaveIdentityPassport {
            get {
                return ResourceManager.GetString("HaveIdentityPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CMND/Hộ chiếu.
        /// </summary>
        public static string IdentityPassport {
            get {
                return ResourceManager.GetString("IdentityPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quốc tịch.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người nộp thuế chưa có MST/CMND/Hộ chiếu.
        /// </summary>
        public static string NotYetIdentityPassport {
            get {
                return ResourceManager.GetString("NotYetIdentityPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số.
        /// </summary>
        public static string NumBirthCertificate {
            get {
                return ResourceManager.GetString("NumBirthCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyển số.
        /// </summary>
        public static string NumBookBirthCertificate {
            get {
                return ResourceManager.GetString("NumBookBirthCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi đăng ký.
        /// </summary>
        public static string RegisterPlace {
            get {
                return ResourceManager.GetString("RegisterPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quan hệ với người nộp thuế.
        /// </summary>
        public static string Relationship {
            get {
                return ResourceManager.GetString("Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn File.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số thuế.
        /// </summary>
        public static string TaxCode {
            get {
                return ResourceManager.GetString("TaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin người phụ thuộc.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
