//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyuyo.BL.Resources.Bonus
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesM014
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesM014()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kyuyo.BL.Resources.Bonus.MessagesM014", typeof(MessagesM014).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hệ thống đang thực hiện tính lương nên bạn không thể chỉnh sửa dữ liệu..
        /// </summary>
        public static string Payroll
        {
            get
            {
                return ResourceManager.GetString("Payroll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File được chọn không đúng định dạng, vui lòng chọn file Excel để import..
        /// </summary>
        public static string ErrorFileFormat
        {
            get
            {
                return ResourceManager.GetString("ErrorFileFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File đã chọn không đúng định dạng, vui lòng click nút "Xuất Template" để lấy file có định dạng đúng..
        /// </summary>
        public static string ErrorColumnNumber
        {
            get
            {
                return ResourceManager.GetString("ErrorColumnNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File đã chọn không có dữ liệu để import..
        /// </summary>
        public static string ErrorRowNumber
        {
            get
            {
                return ResourceManager.GetString("ErrorRowNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vui lòng bổ sung nội dung ở cột D5 để làm diễn giải cho dữ liệu khi import..
        /// </summary>
        public static string PayDesc
        {
            get
            {
                return ResourceManager.GetString("PayDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vui lòng giới hạn nội dung ở cột D5 dưới 200 ký tự để làm diễn giải cho dữ liệu khi import..
        /// </summary>
        public static string MaxLengthPayDesc
        {
            get
            {
                return ResourceManager.GetString("MaxLengthPayDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} {1} không tồn tại..
        /// </summary>
        public static string ErrorExist
        {
            get
            {
                return ResourceManager.GetString("ErrorExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} {1} phải là kiểu số..
        /// </summary>
        public static string FormatNumber
        {
            get
            {
                return ResourceManager.GetString("FormatNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} {1} không được lớn hơn 10..
        /// </summary>
        public static string MaxEmployeeCode
        {
            get
            {
                return ResourceManager.GetString("MaxEmployeeCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} {1} không được rỗng..
        /// </summary>
        public static string Required
        {
            get
            {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} có {1} với phần thập phân không phù hợp..
        /// </summary>
        public static string IsValidDecimal
        {
            get
            {
                return ResourceManager.GetString("IsValidDecimal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} {1} không được lớn hơn 999,999,999..
        /// </summary>
        public static string MaxNumber
        {
            get
            {
                return ResourceManager.GetString("MaxNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Đã import {0}/{1} dòng dữ liệu và xuất log kết quả, vui lòng kiểm tra..
        /// </summary>
        public static string ResultImport
        {
            get
            {
                return ResourceManager.GetString("ResultImport", resourceCulture);
            }
        }
    }
}
