//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyuyo.DA
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class KY_ALLOWANCE_MASTER
    {
    		[Key()]
    	    public int ID { get; set; }
    	    public int COMPANY_ID { get; set; }
    	    public string ALLOWANCE_CD { get; set; }
    	    public string ALLOWANCE_NAME { get; set; }
    	    public string GROUP_CD { get; set; }
    	    public string GROUP_NAME { get; set; }
    	    public decimal VALUE_OFFICAL { get; set; }
    	    public decimal VALUE_PROB { get; set; }
    	    public string UNIT { get; set; }
    	    public string ALLOWANCE_FLG { get; set; }
    	    public System.DateTime EFFECTIVE_DT { get; set; }
    	    public string DELETE_FLAG { get; set; }
    	    public Nullable<System.DateTime> CREATED_DT { get; set; }
    	    public string CREATED_BY { get; set; }
    	    public Nullable<System.DateTime> UPDATED_DT { get; set; }
    	    public string UPDATED_BY { get; set; }
    	    public Nullable<int> MAIN_ID { get; set; }
    	    public Nullable<int> HISTORY_NO { get; set; }
    }
}
