//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyuyo.DA
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class KY_EMPLOYEE_MASTER
    {
    		[Key()]
    	    public int ID { get; set; }
    	    public int COMPANY_ID { get; set; }
    	    public string EMPLOYEE_NO { get; set; }
    	    public string EMPLOYEE_NO_PE { get; set; }
    	    public string EMPLOYEE_NAME { get; set; }
    	    public string EMPLOYEE_NAME_FULL { get; set; }
    	    public string USER_ID { get; set; }
    	    public string PASSWORD { get; set; }
    	    public Nullable<decimal> ABSENCE_NOT_PAY_BF { get; set; }
    	    public Nullable<decimal> ABSENCE_NOT_PAY_AT { get; set; }
    	    public string ADDRESS { get; set; }
    	    public Nullable<System.DateTime> ADDRESS_EFFECTIVE_DT { get; set; }
    	    public string WORK_PLACE { get; set; }
    	    public Nullable<System.DateTime> WORK_PLACE_EFFECTIVE_DT { get; set; }
    	    public string EMAIL { get; set; }
    	    public Nullable<System.DateTime> EMAIL_EFFECTIVE_DT { get; set; }
    	    public string NATIONALITY { get; set; }
    	    public string CONTINENTS { get; set; }
    	    public string IDENTITY_PASSPORT { get; set; }
    	    public string PERSONAL_TAX_CODE { get; set; }
    	    public string UNIVERSITY { get; set; }
    	    public string QUALIFICATION { get; set; }
    	    public string LEVEL { get; set; }
    	    public Nullable<System.DateTime> LEVEL_EFFECTIVE_DT { get; set; }
    	    public string LEVEL_GROUP { get; set; }
    	    public Nullable<System.DateTime> LEVEL_GROUP_EFFECTIVE_DT { get; set; }
    	    public string PHONE_NO { get; set; }
    	    public string CONTRACT_TYPE { get; set; }
    	    public Nullable<System.DateTime> CONTRACT_TYPE_EFFECTIVE_DT { get; set; }
    	    public string EMERGENCY_PHONE_NO { get; set; }
    	    public string EMPLOYEE_TYPE { get; set; }
    	    public Nullable<System.DateTime> EMP_TYPE_EFFECTIVE_DT { get; set; }
    	    public string GENDER { get; set; }
    	    public Nullable<System.DateTime> BIRTH_DT { get; set; }
    	    public Nullable<System.DateTime> ENTRY_DT { get; set; }
    	    public decimal STANDARD_HOURS { get; set; }
    	    public Nullable<System.DateTime> STANDARD_HOURS_EFFECTIVE_DT { get; set; }
    	    public Nullable<System.DateTime> QUIT_DT { get; set; }
    	    public string CONTRACT_FORM { get; set; }
    	    public Nullable<System.DateTime> CONTRACT_FORM_EFECTIVE_DT { get; set; }
    	    public Nullable<System.DateTime> PROBATION_END_DT { get; set; }
    	    public decimal EXCHANGE_RATE_SOCIAL_INSU_SAL { get; set; }
    	    public string INSURANCE { get; set; }
    	    public Nullable<System.DateTime> INSURANCE_EFFECTIVE_DT { get; set; }
    	    public string INSURANCE_UNION_MONTH { get; set; }
    	    public string INSURANCE_CODE { get; set; }
    	    public string HOSPITAL { get; set; }
    	    public Nullable<System.DateTime> HOSPITAL_EFECTIVE_DT { get; set; }
    	    public string PIT { get; set; }
    	    public Nullable<System.DateTime> PIT_EFFECTIVE_DT { get; set; }
    	    public string CERTIFICATE_LIST { get; set; }
    	    public Nullable<System.DateTime> LABOUR_UNION_DT { get; set; }
    	    public string DELETE_FLAG { get; set; }
    	    public Nullable<System.DateTime> CREATED_DT { get; set; }
    	    public string CREATED_BY { get; set; }
    	    public Nullable<System.DateTime> UPDATED_DT { get; set; }
    	    public string UPDATED_BY { get; set; }
    }
}
