//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyuyo.DA
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class KY_SALARY_MASTER
    {
    		[Key()]
    	    public int ID { get; set; }
    	    public string EMPLOYEE_NO { get; set; }
    	    public Nullable<decimal> BASIC_SALARY_OFFICAL { get; set; }
    	    public Nullable<decimal> BASIC_SALARY_PROBATION { get; set; }
    	    public Nullable<decimal> SALARY_HOUR { get; set; }
    	    public Nullable<decimal> SALARY_CAL_SOCIAL_INSU { get; set; }
    	    public string BANK_ACCOUNT { get; set; }
    	    public string BANK_NAME { get; set; }
    	    public string UNIT { get; set; }
    	    public string ALLOWANCE_LIST { get; set; }
    	    public string OT_TYPE { get; set; }
    	    public string FORMULA_CD { get; set; }
    	    public System.DateTime EFFECTIVE_DT { get; set; }
    	    public string DELETE_FLAG { get; set; }
    	    public Nullable<System.DateTime> CREATED_DT { get; set; }
    	    public string CREATED_BY { get; set; }
    	    public Nullable<System.DateTime> UPDATED_DT { get; set; }
    	    public string UPDATED_BY { get; set; }
    	    public Nullable<int> MAIN_ID { get; set; }
    	    public Nullable<int> HISTORY_NO { get; set; }
    	    public Nullable<decimal> EXCHANGE_RATE_SOCIAL_INSU_SAL { get; set; }
    	    public string PRODUCT_SALARY { get; set; }
    	    public string SALARY_UNIT { get; set; }
    }
}
