//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyuyo.DA
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class KY_SALARY_FORMULA_MASTER
    {
    		[Key()]
    	    public int ID { get; set; }
    	    public int COMPANY_ID { get; set; }
    	    public string FORMULA_CD { get; set; }
    	    public string FORMULA_NAME { get; set; }
    	    public string FORMULA_VALUE { get; set; }
    	    public string FORMULA_TYPE { get; set; }
    	    public System.DateTime EFFECTIVE_DT { get; set; }
    	    public string DELETE_FLAG { get; set; }
    	    public Nullable<System.DateTime> CREATED_DT { get; set; }
    	    public string CREATED_BY { get; set; }
    	    public Nullable<System.DateTime> UPDATED_DT { get; set; }
    	    public string UPDATED_BY { get; set; }
    	    public Nullable<int> MAIN_ID { get; set; }
    	    public Nullable<int> HISTORY_NO { get; set; }
    }
}
