//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyuyo.DA
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TB_M_COMPANY
    {
    		[Key()]
    	    public int ID { get; set; }
    	    public string COMPANY_CD { get; set; }
    	    public string COMPANY_NAME { get; set; }
    	    public string ADDRESS { get; set; }
    	    public string COMPANY_TAX_CODE { get; set; }
    	    public string ACTIVE_FLAG { get; set; }
    	    public string PAYROLL_STATUS { get; set; }
    	    public decimal STANDAR_WORKING_DAYS { get; set; }
    	    public decimal COMPANY_AREA { get; set; }
    	    public Nullable<System.DateTime> CREATED_DT { get; set; }
    	    public string CREATED_BY { get; set; }
    	    public Nullable<System.DateTime> UPDATED_DT { get; set; }
    	    public string UPDATED_BY { get; set; }
    }
}
