//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyuyo.DA
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TB_M_SYSTEM
    {
    		[Key()]
    	    public int ID { get; set; }
    	    public string COMPANY_CD { get; set; }
    	    public string CATEGORY { get; set; }
    	    public string CD { get; set; }
    	    public string VALUE { get; set; }
    	    public string CHAR_VALUE_1 { get; set; }
    	    public string CHAR_VALUE_2 { get; set; }
    	    public string CHAR_VALUE_3 { get; set; }
    	    public Nullable<decimal> NUM_VALUE_1 { get; set; }
    	    public Nullable<decimal> NUM_VALUE_2 { get; set; }
    	    public Nullable<decimal> NUM_VALUE_3 { get; set; }
    	    public string REMARK { get; set; }
    	    public Nullable<decimal> LIST_ORDER { get; set; }
    	    public string ACTIVE_FLAG { get; set; }
    	    public Nullable<System.DateTime> CREATED_DT { get; set; }
    	    public string CREATED_BY { get; set; }
    	    public Nullable<System.DateTime> UPDATED_DT { get; set; }
    	    public string UPDATED_BY { get; set; }
    }
}
