//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyuyo.DA
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TB_R_WORKING_TIME
    {
    		[Key()]
    	    public int WORKING_TIME_CD { get; set; }
    	    public string COMPANY_CD { get; set; }
    	    public string EMPLOYEE_NO { get; set; }
    	    public Nullable<decimal> REVISION { get; set; }
    	    public string DEPT_CD { get; set; }
    	    public string WORKING_TITLE { get; set; }
    	    public System.DateTime WORKING_DATE { get; set; }
    	    public string ACT_IN_TIME { get; set; }
    	    public string ACT_OUT_TIME { get; set; }
    	    public Nullable<decimal> WORKING_TIME { get; set; }
    	    public Nullable<decimal> ABSENCE_TIME { get; set; }
    	    public Nullable<decimal> TOTAL_OT_TIME { get; set; }
    	    public Nullable<decimal> LATE_OT_TIME { get; set; }
    	    public Nullable<decimal> TOTAL_LATE_TIME { get; set; }
    	    public Nullable<decimal> DEDUCTED_UNPAID { get; set; }
    	    public Nullable<decimal> DEDUCTED_PAID { get; set; }
    	    public string ATTENDANCE_TYPE { get; set; }
    	    public string WORKING_TYPE { get; set; }
    	    public string SPECIAL_TYPE { get; set; }
    	    public string REMARK { get; set; }
    	    public Nullable<decimal> DEDUCTED_NON_WORK_PLAN { get; set; }
    	    public Nullable<decimal> DEDUCTED_NON_WORK_ACTUAL { get; set; }
    	    public string MAIN_SHIFT { get; set; }
    	    public string CURRENT_SHIFT { get; set; }
    	    public string STD_IN_TIME { get; set; }
    	    public string STD_OUT_TIME { get; set; }
    	    public Nullable<decimal> STD_WORK_HOUR { get; set; }
    	    public string STATUS { get; set; }
    	    public string CONFIRMED_BY { get; set; }
    	    public string WITHDRAWN_BY { get; set; }
    	    public Nullable<System.DateTime> CREATED_DT { get; set; }
    	    public Nullable<System.DateTime> CONFIRMED_DT { get; set; }
    	    public Nullable<System.DateTime> WITHDRAWN_DT { get; set; }
    	    public Nullable<System.DateTime> UPDATED_DT { get; set; }
    }
}
