//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyuyo.BL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kyuyo.BL.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 403: Access denied!.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền truy cập màn hình này, hãy liên hệ với người quản trị hệ thống..
        /// </summary>
        public static string AccessDeniedMsg {
            get {
                return ResourceManager.GetString("AccessDeniedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn file để import.
        /// </summary>
        public static string AlertRequiredImport {
            get {
                return ResourceManager.GetString("AlertRequiredImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn hủy xác nhận kết quả tính lương không?.
        /// </summary>
        public static string CancelCal {
            get {
                return ResourceManager.GetString("CancelCal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng năm đã kết sổ nên không được import dữ liệu..
        /// </summary>
        public static string CloseBook {
            get {
                return ResourceManager.GetString("CloseBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn kết sổ kỳ lương đã chỉ định không?.
        /// </summary>
        public static string ClosingCal {
            get {
                return ResourceManager.GetString("ClosingCal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập File so sánh.
        /// </summary>
        public static string CompareFile {
            get {
                return ResourceManager.GetString("CompareFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn xác nhận kết quả tính lương đã chính xác không?.
        /// </summary>
        public static string ConfirmCal {
            get {
                return ResourceManager.GetString("ConfirmCal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn thêm mới dữ liệu không?.
        /// </summary>
        public static string ConfirmCreate {
            get {
                return ResourceManager.GetString("ConfirmCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn xóa dữ liệu không?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn import dữ liệu không?.
        /// </summary>
        public static string ConfirmImport {
            get {
                return ResourceManager.GetString("ConfirmImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        public static string ConfirmTitle {
            get {
                return ResourceManager.GetString("ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn cập nhật dữ liệu không?.
        /// </summary>
        public static string ConfirmUpdate {
            get {
                return ResourceManager.GetString("ConfirmUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn cập nhật dữ liệu của nhân viên đã chọn trước đó không?.
        /// </summary>
        public static string ConfirmUpdateSelected {
            get {
                return ResourceManager.GetString("ConfirmUpdateSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới dữ liệu thành công..
        /// </summary>
        public static string DataCreated {
            get {
                return ResourceManager.GetString("DataCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dữ liệu thành công..
        /// </summary>
        public static string DataDeleted {
            get {
                return ResourceManager.GetString("DataDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu chưa được khóa hoặc user khác đã mở khóa. Vui lòng kiểm tra..
        /// </summary>
        public static string DataIsLocked {
            get {
                return ResourceManager.GetString("DataIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu..
        /// </summary>
        public static string DataNotFound {
            get {
                return ResourceManager.GetString("DataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật dữ liệu thành công..
        /// </summary>
        public static string DataUpdated {
            get {
                return ResourceManager.GetString("DataUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không đúng định dạng ngày..
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã tồn tại..
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên được chọn đã tồn tại dữ liệu..
        /// </summary>
        public static string ErrorDataExist {
            get {
                return ResourceManager.GetString("ErrorDataExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đã bị xóa bởi người dùng khác..
        /// </summary>
        public static string ErrorDeleted {
            get {
                return ResourceManager.GetString("ErrorDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu thưởng này không phân bổ trong năm có phải không không？.
        /// </summary>
        public static string ErrorDistribution {
            get {
                return ResourceManager.GetString("ErrorDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đã được cập nhật bởi người khác. Vui lòng nhấn nút tìm kiếm rồi thực hiện lại..
        /// </summary>
        public static string ErrorExclusive {
            get {
                return ResourceManager.GetString("ErrorExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn công ty cho chức năng đã chọn.
        /// </summary>
        public static string ErrorNoSelectCompany {
            get {
                return ResourceManager.GetString("ErrorNoSelectCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn nhân viên.
        /// </summary>
        public static string ErrorNoSelectEmp {
            get {
                return ResourceManager.GetString("ErrorNoSelectEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn mode cho chức năng đã chọn.
        /// </summary>
        public static string ErrorNoSelectMode {
            get {
                return ResourceManager.GetString("ErrorNoSelectMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên được chọn đã tồn tại dữ liệu.
        /// </summary>
        public static string ErrorSelectEmp {
            get {
                return ResourceManager.GetString("ErrorSelectEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System error!.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact administrator for support..
        /// </summary>
        public static string ExceptionMsg {
            get {
                return ResourceManager.GetString("ExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File đã chọn không có dữ liệu để import.
        /// </summary>
        public static string FileNoData {
            get {
                return ResourceManager.GetString("FileNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File được chọn không đúng định dạng, vui lòng chọn file Excel để import.
        /// </summary>
        public static string FormatExcel {
            get {
                return ResourceManager.GetString("FormatExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File đã chọn không đúng định dạng, vui lòng click nút &quot;Xuất Template&quot; để lấy file có định dạng đúng.
        /// </summary>
        public static string FormatTemplate {
            get {
                return ResourceManager.GetString("FormatTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã import {0}/{1} dòng dữ liệu và xuất log kết quả, vui lòng kiểm tra..
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dòng đăng ký mới: {0} dòng.
        /// </summary>
        public static string ImportInsert {
            get {
                return ResourceManager.GetString("ImportInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dòng cập nhật: {0} dòng.
        /// </summary>
        public static string ImportUpdate {
            get {
                return ResourceManager.GetString("ImportUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Code or Password..
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hiệu lực không đúng định dạng ngày..
        /// </summary>
        public static string M009DateFormat {
            get {
                return ResourceManager.GetString("M009DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày kết thức hiệu lực phải sau ngày bắt đầu hiệu lực.
        /// </summary>
        public static string M009FutureCertificate {
            get {
                return ResourceManager.GetString("M009FutureCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập Ngày bắt đầu hiệu lực của bằng cấp.
        /// </summary>
        public static string M009RequiredCertificate {
            get {
                return ResourceManager.GetString("M009RequiredCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không quá {1} ký tự..
        /// </summary>
        public static string Maxlength {
            get {
                return ResourceManager.GetString("Maxlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được lớn hơn {1}.
        /// </summary>
        public static string MaxNumber {
            get {
                return ResourceManager.GetString("MaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn file để import.
        /// </summary>
        public static string NoFileSelect {
            get {
                return ResourceManager.GetString("NoFileSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404: Page not found!.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page you want to access is not available, please try again..
        /// </summary>
        public static string PageNotFoundMsg {
            get {
                return ResourceManager.GetString("PageNotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống đang thực hiện tính lương nên bạn không thể chỉnh sửa dữ liệu.
        /// </summary>
        public static string Payroll {
            get {
                return ResourceManager.GetString("Payroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn yêu cầu xác nhận kết quả tính lương không?.
        /// </summary>
        public static string RequestCal {
            get {
                return ResourceManager.GetString("RequestCal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập {0}..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số tháng phân bổ..
        /// </summary>
        public static string RequiredDistributionMonths {
            get {
                return ResourceManager.GetString("RequiredDistributionMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication required..
        /// </summary>
        public static string RequiredLogin {
            get {
                return ResourceManager.GetString("RequiredLogin", resourceCulture);
            }
        }
    }
}
