//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyuyo.BL.Resources.Allowance {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsM007 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsM007() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kyuyo.BL.Resources.Allowance.StringsM007", typeof(StringsM007).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày áp dụng.
        /// </summary>
        public static string AffectiveDt {
            get {
                return ResourceManager.GetString("AffectiveDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã trợ cấp/phụ cấp.
        /// </summary>
        public static string AllowanceCd {
            get {
                return ResourceManager.GetString("AllowanceCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên trợ cấp/phụ cấp.
        /// </summary>
        public static string AllowanceName {
            get {
                return ResourceManager.GetString("AllowanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS phụ cấp/trợ cấp tính OT.
        /// </summary>
        public static string AllowanceOT {
            get {
                return ResourceManager.GetString("AllowanceOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS phụ cấp/trợ cấp tính trợ cấp thôi việc.
        /// </summary>
        public static string AllowanceTV {
            get {
                return ResourceManager.GetString("AllowanceTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS phụ cấp/trợ cấp tính phép năm.
        /// </summary>
        public static string AllowanceYear {
            get {
                return ResourceManager.GetString("AllowanceYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BHTN.
        /// </summary>
        public static string BHTN {
            get {
                return ResourceManager.GetString("BHTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BHXH.
        /// </summary>
        public static string BHXH {
            get {
                return ResourceManager.GetString("BHXH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BHYT.
        /// </summary>
        public static string BHYT {
            get {
                return ResourceManager.GetString("BHYT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty.
        /// </summary>
        public static string CompanyCd {
            get {
                return ResourceManager.GetString("CompanyCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import master trợ cấp/phụ cấp.
        /// </summary>
        public static string ImportMasterTitle {
            get {
                return ResourceManager.GetString("ImportMasterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIT.
        /// </summary>
        public static string PIT {
            get {
                return ResourceManager.GetString("PIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các loại phúc lợi xã hội phải đóng.
        /// </summary>
        public static string PolicyTitle {
            get {
                return ResourceManager.GetString("PolicyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các loại dữ liệu lương bao gồm phụ cấp này.
        /// </summary>
        public static string PolicyTitle2 {
            get {
                return ResourceManager.GetString("PolicyTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký/Cập nhật/Xóa dữ liệu trợ cấp/phụ cấp.
        /// </summary>
        public static string ProsessTitle {
            get {
                return ResourceManager.GetString("ProsessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinh phí công đoàn.
        /// </summary>
        public static string Syndicate {
            get {
                return ResourceManager.GetString("Syndicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trợ cấp/phụ cấp.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trợ cấp.
        /// </summary>
        public static string Type1 {
            get {
                return ResourceManager.GetString("Type1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ cấp.
        /// </summary>
        public static string Type2 {
            get {
                return ResourceManager.GetString("Type2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền chính thức.
        /// </summary>
        public static string ValueOffical {
            get {
                return ResourceManager.GetString("ValueOffical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền thử việc.
        /// </summary>
        public static string ValueProb {
            get {
                return ResourceManager.GetString("ValueProb", resourceCulture);
            }
        }
    }
}
