//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyuyo.BL.Resources.Deparment {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesM020 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesM020() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kyuyo.BL.Resources.Deparment.MessagesM020", typeof(MessagesM020).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ phận đang chọn đã được sử dụng ở các dữ liệu liên quan khác, không được phép thay đổi mã bộ phận..
        /// </summary>
        public static string ErrorDeptChage {
            get {
                return ResourceManager.GetString("ErrorDeptChage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ phận đang chọn đã được sử dụng ở các dữ liệu liên quan khác, hãy cho &quot;Sử dụng&quot; thành ON..
        /// </summary>
        public static string ErrorDeptUsed {
            get {
                return ResourceManager.GetString("ErrorDeptUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bộ phận đã tồn tại..
        /// </summary>
        public static string ErrorUnique {
            get {
                return ResourceManager.GetString("ErrorUnique", resourceCulture);
            }
        }
    }
}
