//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyuyo.BL.Resources.Employee {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsM009 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsM009() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kyuyo.BL.Resources.Employee.StringsM009", typeof(StringsM009).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số ngày nghỉ không lương sau 2008.
        /// </summary>
        public static string AbsenceNotPayDaysAfter2008 {
            get {
                return ResourceManager.GetString("AbsenceNotPayDaysAfter2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số ngày nghỉ không lương trước 2008.
        /// </summary>
        public static string AbsenceNotPayDaysBefore2008 {
            get {
                return ResourceManager.GetString("AbsenceNotPayDaysBefore2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm bộ phận.
        /// </summary>
        public static string AddDepartment {
            get {
                return ResourceManager.GetString("AddDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách chứng chỉ.
        /// </summary>
        public static string Certificates {
            get {
                return ResourceManager.GetString("Certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty.
        /// </summary>
        public static string CompanyCd {
            get {
                return ResourceManager.GetString("CompanyCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Châu lục.
        /// </summary>
        public static string Continents {
            get {
                return ResourceManager.GetString("Continents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình thức hợp đồng.
        /// </summary>
        public static string ContractForm {
            get {
                return ResourceManager.GetString("ContractForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại hợp đồng.
        /// </summary>
        public static string ContractType {
            get {
                return ResourceManager.GetString("ContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ phận.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày áp dụng.
        /// </summary>
        public static string EffectiveDt {
            get {
                return ResourceManager.GetString("EffectiveDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại khẩn cấp.
        /// </summary>
        public static string EmergencyNumber {
            get {
                return ResourceManager.GetString("EmergencyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên.
        /// </summary>
        public static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên có dấu.
        /// </summary>
        public static string EmployeeNameFull {
            get {
                return ResourceManager.GetString("EmployeeNameFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số nhân viên.
        /// </summary>
        public static string EmployeeNo {
            get {
                return ResourceManager.GetString("EmployeeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số nhân viên PE.
        /// </summary>
        public static string EmployeeNoPE {
            get {
                return ResourceManager.GetString("EmployeeNoPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại nhân viên.
        /// </summary>
        public static string EmployeeType {
            get {
                return ResourceManager.GetString("EmployeeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày vào công ty.
        /// </summary>
        public static string EntryDate {
            get {
                return ResourceManager.GetString("EntryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi ĐK khám chữa bệnh.
        /// </summary>
        public static string Hospital {
            get {
                return ResourceManager.GetString("Hospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CMND/Passport.
        /// </summary>
        public static string IdentifyPassport {
            get {
                return ResourceManager.GetString("IdentifyPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hết hạn.
        /// </summary>
        public static string InActiveDate {
            get {
                return ResourceManager.GetString("InActiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hết hiệu lực.
        /// </summary>
        public static string InactiveDt {
            get {
                return ResourceManager.GetString("InactiveDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bao gồm nhân viên thôi việc.
        /// </summary>
        public static string IncludeRetireEmployee {
            get {
                return ResourceManager.GetString("IncludeRetireEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info Change.
        /// </summary>
        public static string InfoChange {
            get {
                return ResourceManager.GetString("InfoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số đóng BH.
        /// </summary>
        public static string InsuCode {
            get {
                return ResourceManager.GetString("InsuCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách phúc lợi xã hội.
        /// </summary>
        public static string Insurances {
            get {
                return ResourceManager.GetString("Insurances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạng mục.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấp bậc.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân cấp nhân sự.
        /// </summary>
        public static string LevelGroup {
            get {
                return ResourceManager.GetString("LevelGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ phận chính.
        /// </summary>
        public static string MainDept {
            get {
                return ResourceManager.GetString("MainDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng bắt đầu tham gia BH.
        /// </summary>
        public static string MonthJoinInsurance {
            get {
                return ResourceManager.GetString("MonthJoinInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quốc tịch.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số thuế.
        /// </summary>
        public static string NumberTaxCode {
            get {
                return ResourceManager.GetString("NumberTaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIT.
        /// </summary>
        public static string PIT {
            get {
                return ResourceManager.GetString("PIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày kết thúc thử việc.
        /// </summary>
        public static string ProbationEndDate {
            get {
                return ResourceManager.GetString("ProbationEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trình độ chuyên môn.
        /// </summary>
        public static string Qualification {
            get {
                return ResourceManager.GetString("Qualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày thôi việc.
        /// </summary>
        public static string RetireDate {
            get {
                return ResourceManager.GetString("RetireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số giờ làm việc tiêu chuẩn.
        /// </summary>
        public static string StandardHours {
            get {
                return ResourceManager.GetString("StandardHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ.
        /// </summary>
        public static string TitleClass {
            get {
                return ResourceManager.GetString("TitleClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import thông tin nhân viên.
        /// </summary>
        public static string TitleImport {
            get {
                return ResourceManager.GetString("TitleImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký/Cập nhật/Xóa thông tin nhân viên.
        /// </summary>
        public static string TitleInfo {
            get {
                return ResourceManager.GetString("TitleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày vào công đoàn.
        /// </summary>
        public static string UnionJoinDate {
            get {
                return ResourceManager.GetString("UnionJoinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường tốt nghiệp.
        /// </summary>
        public static string University {
            get {
                return ResourceManager.GetString("University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cập nhật.
        /// </summary>
        public static string UpdatedDt {
            get {
                return ResourceManager.GetString("UpdatedDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có hiệu lực từ.
        /// </summary>
        public static string ValidateFrom {
            get {
                return ResourceManager.GetString("ValidateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị thay đổi.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi làm việc.
        /// </summary>
        public static string WorkingPlace {
            get {
                return ResourceManager.GetString("WorkingPlace", resourceCulture);
            }
        }
    }
}
