//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyuyo.BL.Resources.ReportList {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsM019 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsM019() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kyuyo.BL.Resources.ReportList.StringsM019", typeof(StringsM019).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dương lịch.
        /// </summary>
        public static string CalByCalendar {
            get {
                return ResourceManager.GetString("CalByCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo theo ngày.
        /// </summary>
        public static string DailyReport {
            get {
                return ResourceManager.GetString("DailyReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết lương từng nhân vviên.
        /// </summary>
        public static string DetailEmployeeSalary {
            get {
                return ResourceManager.GetString("DetailEmployeeSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin nhân viên.
        /// </summary>
        public static string EmployeeInfo {
            get {
                return ResourceManager.GetString("EmployeeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất báo cáo.
        /// </summary>
        public static string ExportReportBtn {
            get {
                return ResourceManager.GetString("ExportReportBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ～.
        /// </summary>
        public static string FromTo {
            get {
                return ResourceManager.GetString("FromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách người phụ thuộc.
        /// </summary>
        public static string ListDependentPerson {
            get {
                return ResourceManager.GetString("ListDependentPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách phụ cấp chứng chỉ bằng cấp.
        /// </summary>
        public static string ListSubdizeCertificate {
            get {
                return ResourceManager.GetString("ListSubdizeCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý lao động.
        /// </summary>
        public static string MangeEmp {
            get {
                return ResourceManager.GetString("MangeEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo theo tháng.
        /// </summary>
        public static string MonthlyReport {
            get {
                return ResourceManager.GetString("MonthlyReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số quản lý nhân viên.
        /// </summary>
        public static string NoteManageEmp {
            get {
                return ResourceManager.GetString("NoteManageEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuế thu nhập cá nhân năm.
        /// </summary>
        public static string PersonalTaxPerYear {
            get {
                return ResourceManager.GetString("PersonalTaxPerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo tình hình thay đổi về lao động 6 tháng.
        /// </summary>
        public static string ReportChangeHR {
            get {
                return ResourceManager.GetString("ReportChangeHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo tính hình sử dụng người lao động nước ngoài 6 tháng.
        /// </summary>
        public static string ReportUsingOtherEmployee {
            get {
                return ResourceManager.GetString("ReportUsingOtherEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng lương điều chỉnh.
        /// </summary>
        public static string TableAdjustSalary {
            get {
                return ResourceManager.GetString("TableAdjustSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng tiền thưởng.
        /// </summary>
        public static string TableBonusMoney {
            get {
                return ResourceManager.GetString("TableBonusMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng tính phí đoàn phí công đoàn.
        /// </summary>
        public static string TableCalCostFederation {
            get {
                return ResourceManager.GetString("TableCalCostFederation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng tính bảo hiểm bắt buộc.
        /// </summary>
        public static string TableCalRequireInsurrence {
            get {
                return ResourceManager.GetString("TableCalRequireInsurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng tổng hợp thu nhập trong năm (NET).
        /// </summary>
        public static string TableCollectSalaryInyear {
            get {
                return ResourceManager.GetString("TableCollectSalaryInyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng chi phí lương tháng.
        /// </summary>
        public static string TableCostSalary {
            get {
                return ResourceManager.GetString("TableCostSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng lương nhân viên người nước ngoài.
        /// </summary>
        public static string TableEmployeeSalaryOther {
            get {
                return ResourceManager.GetString("TableEmployeeSalaryOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng lương nhân viên người Việt Nam.
        /// </summary>
        public static string TableEmployeeSalaryVn {
            get {
                return ResourceManager.GetString("TableEmployeeSalaryVn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng tổng hợp lương.
        /// </summary>
        public static string TableGeneralSalary {
            get {
                return ResourceManager.GetString("TableGeneralSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng lương nhân viên bán thời gian người nước ngoài.
        /// </summary>
        public static string TablePartTimeEmployeeSalaryOther {
            get {
                return ResourceManager.GetString("TablePartTimeEmployeeSalaryOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng lương nhân viên bán thời gian người Việt Nam.
        /// </summary>
        public static string TablePartTimeEmployeeSalaryVn {
            get {
                return ResourceManager.GetString("TablePartTimeEmployeeSalaryVn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán lương qua ngân hàng.
        /// </summary>
        public static string TablePayByBank {
            get {
                return ResourceManager.GetString("TablePayByBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng tính thuế TNCN hàng tháng.
        /// </summary>
        public static string TablePersonalTax {
            get {
                return ResourceManager.GetString("TablePersonalTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng tiền trợ cấp BHXH.
        /// </summary>
        public static string TableSubdizeInsurrence {
            get {
                return ResourceManager.GetString("TableSubdizeInsurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng tính trợ cấp thôi việc.
        /// </summary>
        public static string TableSubdizeUnEmployment {
            get {
                return ResourceManager.GetString("TableSubdizeUnEmployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách báo cáo.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
