//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyuyo.BL.Resources.WorkingTimeChangeRefer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesM018 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesM018() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kyuyo.BL.Resources.WorkingTimeChangeRefer.MessagesM018", typeof(MessagesM018).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File đã chọn không đúng định dạng, vui lòng click nút &quot;Xuất Template&quot; để lấy file có định dạng đúng..
        /// </summary>
        public static string ErrorColumnNumber {
            get {
                return ResourceManager.GetString("ErrorColumnNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File được chọn không đúng định dạng, vui lòng chọn file Excel để so sánh..
        /// </summary>
        public static string ErrorCompareFileFormat {
            get {
                return ResourceManager.GetString("ErrorCompareFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Mã nhân viên không được rỗng.
        /// </summary>
        public static string ErrorEmpEmpty {
            get {
                return ResourceManager.GetString("ErrorEmpEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Mã nhân viên không tồn tại.
        /// </summary>
        public static string ErrorEmpNotExist {
            get {
                return ResourceManager.GetString("ErrorEmpNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File được chọn không đúng định dạng, vui lòng chọn file Excel để import..
        /// </summary>
        public static string ErrorImportFileFormat {
            get {
                return ResourceManager.GetString("ErrorImportFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu tính lương đã kết sổ, không thể thực hiện import dữ liệu.
        /// </summary>
        public static string ErrorIsClose {
            get {
                return ResourceManager.GetString("ErrorIsClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tháng tính lương.
        /// </summary>
        public static string ErrorMonthEmpty {
            get {
                return ResourceManager.GetString("ErrorMonthEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Số giờ bị trừ lương phải là kiểu số.
        /// </summary>
        public static string ErrorNoSalaryHourDiffNotNumber {
            get {
                return ResourceManager.GetString("ErrorNoSalaryHourDiffNotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File đã chọn không có dữ liệu để import..
        /// </summary>
        public static string ErrorRowNumber {
            get {
                return ResourceManager.GetString("ErrorRowNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Tổng thời gian làm khuya và Số giờ bị trừ lương không được lớn hơn 24.
        /// </summary>
        public static string ErrorTotalLateAndNoSalaryHourNotValid {
            get {
                return ResourceManager.GetString("ErrorTotalLateAndNoSalaryHourNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Tổng thời gian làm khuya phải là kiểu số.
        /// </summary>
        public static string ErrorTotalLateDifNotNumber {
            get {
                return ResourceManager.GetString("ErrorTotalLateDifNotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Tổng thời gian OT và Số giờ bị trừ lương không được lớn hơn 24.
        /// </summary>
        public static string ErrorTotalOtAndNoSalaryHourNotValid {
            get {
                return ResourceManager.GetString("ErrorTotalOtAndNoSalaryHourNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Tổng thời gian OT phải là kiểu số.
        /// </summary>
        public static string ErrorTotalOtDifNotNumber {
            get {
                return ResourceManager.GetString("ErrorTotalOtDifNotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Tổng thời gian OT khuya phải là kiểu số.
        /// </summary>
        public static string ErrorTotalOtLateDifNotNumber {
            get {
                return ResourceManager.GetString("ErrorTotalOtLateDifNotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Tổng thời gian OT khuya không được lớn hơn tổng thời gian làm khuya.
        /// </summary>
        public static string ErrorTotalOtLateLargerThanTotalLate {
            get {
                return ResourceManager.GetString("ErrorTotalOtLateLargerThanTotalLate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Tổng thời gian OT khuya không được lớn hơn tổng thời gian OT.
        /// </summary>
        public static string ErrorTotalOtLateLargerThanTotalOt {
            get {
                return ResourceManager.GetString("ErrorTotalOtLateLargerThanTotalOt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Loại ngày làm việc không tồn tại.
        /// </summary>
        public static string ErrorWkDateTypeFileExcelNotExist {
            get {
                return ResourceManager.GetString("ErrorWkDateTypeFileExcelNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Ngày làm việc phải theo định dạng yyyyMMdd.
        /// </summary>
        public static string ErrorWorkingDateFormatWrong {
            get {
                return ResourceManager.GetString("ErrorWorkingDateFormatWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Ngày làm việc không được rỗng.
        /// </summary>
        public static string ErrorWorkingDateNotExist {
            get {
                return ResourceManager.GetString("ErrorWorkingDateNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tháng năm.
        /// </summary>
        public static string ErrorYearMonthEmpty {
            get {
                return ResourceManager.GetString("ErrorYearMonthEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống đang thực hiện tính lương nên bạn không thể chỉnh sửa dữ liệu..
        /// </summary>
        public static string Payroll {
            get {
                return ResourceManager.GetString("Payroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã import {0}/{1} dòng dữ liệu và xuất log kết quả, vui lòng kiểm tra.
        /// </summary>
        public static string ResultImport {
            get {
                return ResourceManager.GetString("ResultImport", resourceCulture);
            }
        }
    }
}
