//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyuyo.BL.Resources.ImportWorkingTime {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsM015 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsM015() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kyuyo.BL.Resources.ImportWorkingTime.StringsM015", typeof(StringsM015).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng thời gian vắng.
        /// </summary>
        public static string AbsenceTime {
            get {
                return ResourceManager.GetString("AbsenceTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ thực tế vào.
        /// </summary>
        public static string ActInTime {
            get {
                return ResourceManager.GetString("ActInTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ thực tế ra.
        /// </summary>
        public static string ActOutTime {
            get {
                return ResourceManager.GetString("ActOutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái làm việc.
        /// </summary>
        public static string AttendanceType {
            get {
                return ResourceManager.GetString("AttendanceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số ngày phép bị trừ.
        /// </summary>
        public static string DeductedPaid {
            get {
                return ResourceManager.GetString("DeductedPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số giờ bị trừ lương.
        /// </summary>
        public static string DeductedUnpaind {
            get {
                return ResourceManager.GetString("DeductedUnpaind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên.
        /// </summary>
        public static string EmployeeNo {
            get {
                return ResourceManager.GetString("EmployeeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import mới.
        /// </summary>
        public static string ImportNew {
            get {
                return ResourceManager.GetString("ImportNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại Import.
        /// </summary>
        public static string ImportType {
            get {
                return ResourceManager.GetString("ImportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import dữ liệu chấm công.
        /// </summary>
        public static string ImportWT {
            get {
                return ResourceManager.GetString("ImportWT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng thời gian OT khuya.
        /// </summary>
        public static string LateOtTime {
            get {
                return ResourceManager.GetString("LateOtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca làm việc.
        /// </summary>
        public static string MainShift {
            get {
                return ResourceManager.GetString("MainShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng năm.
        /// </summary>
        public static string MonthYear {
            get {
                return ResourceManager.GetString("MonthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày đặc biệt.
        /// </summary>
        public static string SpecialType {
            get {
                return ResourceManager.GetString("SpecialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái duyệt.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ bắt đầu làm việc tiêu chuẩn.
        /// </summary>
        public static string StdInTime {
            get {
                return ResourceManager.GetString("StdInTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ kết thúc làm việc tiêu chuẩn.
        /// </summary>
        public static string StdOutTime {
            get {
                return ResourceManager.GetString("StdOutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số giờ làm việc tiêu chuẩn.
        /// </summary>
        public static string StdWorkHour {
            get {
                return ResourceManager.GetString("StdWorkHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import dữ liệu chấm công.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng thời gian làm khuya.
        /// </summary>
        public static string TotalLateTime {
            get {
                return ResourceManager.GetString("TotalLateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng thời gian OT.
        /// </summary>
        public static string TotalOtTime {
            get {
                return ResourceManager.GetString("TotalOtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày làm việc.
        /// </summary>
        public static string WorkingDate {
            get {
                return ResourceManager.GetString("WorkingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng thời giờ làm việc.
        /// </summary>
        public static string WorkingTime {
            get {
                return ResourceManager.GetString("WorkingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại ngày làm việc.
        /// </summary>
        public static string WorkingType {
            get {
                return ResourceManager.GetString("WorkingType", resourceCulture);
            }
        }
    }
}
