//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyuyo.BL.Resources.Salary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesM012 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesM012() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kyuyo.BL.Resources.Salary.MessagesM012", typeof(MessagesM012).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} {1} phải theo định dạng yyyyMMdd.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập Thời gian được hưởng (Từ ngày) cho phụ cấp {0}.
        /// </summary>
        public static string ErrorAllowanceNull {
            get {
                return ResourceManager.GetString("ErrorAllowanceNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập Lương chính thức hoặc Đơn giá lương giờ.
        /// </summary>
        public static string ErrorBasicSalaryAndPriceHourEmpty {
            get {
                return ResourceManager.GetString("ErrorBasicSalaryAndPriceHourEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lương chính thức không được lớn hơn 999,999,999.
        /// </summary>
        public static string ErrorBasicSalaryToLarge {
            get {
                return ResourceManager.GetString("ErrorBasicSalaryToLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn Công ty ở vùng search và click nút Tìm kiếm trước khi thêm mới dữ liệu.
        /// </summary>
        public static string ErrorCompanyCdEmpty {
            get {
                return ResourceManager.GetString("ErrorCompanyCdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tồn tại thông tin cơ bản tính lương có cùng ngày áp dụng.
        /// </summary>
        public static string ErrorDataExist {
            get {
                return ResourceManager.GetString("ErrorDataExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đã bị xóa bởi người dùng khác.
        /// </summary>
        public static string ErrorDataWasDelete {
            get {
                return ResourceManager.GetString("ErrorDataWasDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đã được cập nhật bởi người khác. Vui lòng nhấn nút tìm kiếm rồi thực hiện lại.
        /// </summary>
        public static string ErrorDataWasModify {
            get {
                return ResourceManager.GetString("ErrorDataWasModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập Ngày áp dụng.
        /// </summary>
        public static string ErrorEffectiveDtEmpty {
            get {
                return ResourceManager.GetString("ErrorEffectiveDtEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn Nhân viên.
        /// </summary>
        public static string ErrorEmployeeEmpty {
            get {
                return ResourceManager.GetString("ErrorEmployeeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn Đơn vị tính lương chính thức.
        /// </summary>
        public static string ErrorForeignCurNull {
            get {
                return ResourceManager.GetString("ErrorForeignCurNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập Tỷ giá lương tính BHXH.
        /// </summary>
        public static string ErrorInsuranceCalSalaryRateNull {
            get {
                return ResourceManager.GetString("ErrorInsuranceCalSalaryRateNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỷ giá lương tính BHXH không được lớn hơn 9,999,999.
        /// </summary>
        public static string ErrorInsuranceCalSalaryRateToLarge {
            get {
                return ResourceManager.GetString("ErrorInsuranceCalSalaryRateToLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lương tính BHXH không được lớn hơn 999,999,999.
        /// </summary>
        public static string ErrorInsuranceCalSalaryToLarge {
            get {
                return ResourceManager.GetString("ErrorInsuranceCalSalaryToLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn Loại OT.
        /// </summary>
        public static string ErrorOTTypeNull {
            get {
                return ResourceManager.GetString("ErrorOTTypeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn giá lương giờ (part time) không được lớn hơn 9,999,999.
        /// </summary>
        public static string ErrorPriceHoursToLarge {
            get {
                return ResourceManager.GetString("ErrorPriceHoursToLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lương thử việc không được lớn hơn 999,999,999.
        /// </summary>
        public static string ErrorProbationSalaryToLarge {
            get {
                return ResourceManager.GetString("ErrorProbationSalaryToLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn Công thức tính Lương.
        /// </summary>
        public static string ErrorSalaryFormularNull {
            get {
                return ResourceManager.GetString("ErrorSalaryFormularNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn Đơn vị tiền trả lương.
        /// </summary>
        public static string ErrorSalaryUnitNull {
            get {
                return ResourceManager.GetString("ErrorSalaryUnitNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập Thời gian được hưởng (Từ ngày) cho trợ cấp {0}.
        /// </summary>
        public static string ErrorSubsidizeNull {
            get {
                return ResourceManager.GetString("ErrorSubsidizeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Số phần tử của {1} phải giống với số phần tử của Các phụ cấp được nhận.
        /// </summary>
        public static string ListDate {
            get {
                return ResourceManager.GetString("ListDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} {1} không được lớn hơn {2} ký tự.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} {1} không được lớn hơn 999,999,999.
        /// </summary>
        public static string MaxNumber1 {
            get {
                return ResourceManager.GetString("MaxNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} {1} không được lớn hơn 9,999,999.
        /// </summary>
        public static string MaxNumber2 {
            get {
                return ResourceManager.GetString("MaxNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} {1} không tồn tại.
        /// </summary>
        public static string NotExist {
            get {
                return ResourceManager.GetString("NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} {1} phải là kiểu số.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} {1} có phần thập phân không phù hợp.
        /// </summary>
        public static string PointLength {
            get {
                return ResourceManager.GetString("PointLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Lương theo sản phẩm phải là 0 hoặc 1.
        /// </summary>
        public static string ProductSalary {
            get {
                return ResourceManager.GetString("ProductSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} {1} không được rỗng.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Lương cơ bản chính thức hoặc Đơn giá lương giờ không được rỗng.
        /// </summary>
        public static string RequiredSalary {
            get {
                return ResourceManager.GetString("RequiredSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Dữ liệu thông tin cơ bản tính lương của nhân viên {1} chưa tồn tại.
        /// </summary>
        public static string SalaryNotExist {
            get {
                return ResourceManager.GetString("SalaryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng {0} Loại lương phải là &quot;GROSS&quot; hoặc &quot;NET&quot;.
        /// </summary>
        public static string SalaryType {
            get {
                return ResourceManager.GetString("SalaryType", resourceCulture);
            }
        }
    }
}
