//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyuyo.BL.Resources.Salary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsM012 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsM012() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kyuyo.BL.Resources.Salary.StringsM012", typeof(StringsM012).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản.
        /// </summary>
        public static string AccountNo {
            get {
                return ResourceManager.GetString("AccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ cấp.
        /// </summary>
        public static string Allowance {
            get {
                return ResourceManager.GetString("Allowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày kết thúc phụ cấp.
        /// </summary>
        public static string AllowanceEndDt {
            get {
                return ResourceManager.GetString("AllowanceEndDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các Phụ cấp được nhận có mã phụ cấp.
        /// </summary>
        public static string AllowanceList {
            get {
                return ResourceManager.GetString("AllowanceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu phụ cấp.
        /// </summary>
        public static string AllowanceStartDt {
            get {
                return ResourceManager.GetString("AllowanceStartDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản ngân hàng.
        /// </summary>
        public static string BankAccount {
            get {
                return ResourceManager.GetString("BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên ngân hàng.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lương chính thức.
        /// </summary>
        public static string BasicSalary {
            get {
                return ResourceManager.GetString("BasicSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lương cơ bản chính thức.
        /// </summary>
        public static string BasicSalaryOffical {
            get {
                return ResourceManager.GetString("BasicSalaryOffical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ phận.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày áp dụng.
        /// </summary>
        public static string EffectiveDt {
            get {
                return ResourceManager.GetString("EffectiveDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên.
        /// </summary>
        public static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên.
        /// </summary>
        public static string EmployeeNo {
            get {
                return ResourceManager.GetString("EmployeeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ～.
        /// </summary>
        public static string FromTo {
            get {
                return ResourceManager.GetString("FromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import mức lương mới.
        /// </summary>
        public static string ImportNewSalary {
            get {
                return ResourceManager.GetString("ImportNewSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import dữ liệu lương.
        /// </summary>
        public static string ImportSalary {
            get {
                return ResourceManager.GetString("ImportSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lương tính BHXH.
        /// </summary>
        public static string InsuranceCalSalary {
            get {
                return ResourceManager.GetString("InsuranceCalSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỷ giá tính lương BHXH.
        /// </summary>
        public static string InsuranceCalSalaryRate {
            get {
                return ResourceManager.GetString("InsuranceCalSalaryRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại OT.
        /// </summary>
        public static string OTType {
            get {
                return ResourceManager.GetString("OTType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lương thử việc.
        /// </summary>
        public static string ProbationSalary {
            get {
                return ResourceManager.GetString("ProbationSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lương sản phẩm.
        /// </summary>
        public static string ProductSalary {
            get {
                return ResourceManager.GetString("ProductSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công thức tính lương.
        /// </summary>
        public static string SalaryFormular {
            get {
                return ResourceManager.GetString("SalaryFormular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROSS.
        /// </summary>
        public static string SalaryGross {
            get {
                return ResourceManager.GetString("SalaryGross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn giá lương giờ.
        /// </summary>
        public static string SalaryHour {
            get {
                return ResourceManager.GetString("SalaryHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin master lương.
        /// </summary>
        public static string SalaryInfo {
            get {
                return ResourceManager.GetString("SalaryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách master lương.
        /// </summary>
        public static string SalaryMasterList {
            get {
                return ResourceManager.GetString("SalaryMasterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NET.
        /// </summary>
        public static string SalaryNet {
            get {
                return ResourceManager.GetString("SalaryNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tiền trả lương.
        /// </summary>
        public static string SalaryUnit {
            get {
                return ResourceManager.GetString("SalaryUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trợ cấp.
        /// </summary>
        public static string Subsidize {
            get {
                return ResourceManager.GetString("Subsidize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Lương.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại nhóm nhận OT.
        /// </summary>
        public static string TypeOT {
            get {
                return ResourceManager.GetString("TypeOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tiền lương.
        /// </summary>
        public static string UnitCur {
            get {
                return ResourceManager.GetString("UnitCur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn giá lương giờ (parttime).
        /// </summary>
        public static string UnitPriceHours {
            get {
                return ResourceManager.GetString("UnitPriceHours", resourceCulture);
            }
        }
    }
}
